Imports System
Imports DevExpress.XtraCharts
Imports DevExpress.XtraEditors

Namespace TwoBoundSeriesInPanes
    Partial Public Class MainForm
        Inherits XtraForm

        Public Sub New()
            InitializeComponent()
            ' This line of code is generated by Data Source Configuration Wizard
            gspTableAdapter.Fill(gspDataSet.GSP)
        End Sub

        Private Sub OnFormLoad(ByVal sender As Object, ByVal e As EventArgs) Handles Me.Load
            Dim year2003Series As New Series()
            year2003Series.Name = "2003"
            year2003Series.ArgumentDataMember = "Region"
            year2003Series.ValueDataMembers(0) = "GSP"
            year2003Series.FilterString = "[Year] == 2003"

            Dim year2004Series As New Series()
            year2004Series.Name = "2004"
            year2004Series.ArgumentDataMember = "Region"
            year2004Series.ValueDataMembers(0) = "GSP"
            year2004Series.FilterString = "[Year] == 2004"

            chartControl.Series.AddRange(year2003Series, year2004Series)

            Dim diagram As XYDiagram = CType(chartControl.Diagram, XYDiagram)
            Dim secondPane As New XYDiagramPane("Second Pane")
            diagram.Panes.Add(secondPane)

            Dim secondLegend As New Legend("Second Legend") With { _
                .DockTarget = secondPane, _
                .AlignmentHorizontal = LegendAlignmentHorizontal.Right, _
                .AlignmentVertical = LegendAlignmentVertical.Top _
            }
            chartControl.Legends.Add(secondLegend)

            Dim xyView As XYDiagramSeriesViewBase = CType(year2004Series.View, XYDiagramSeriesViewBase)
            year2004Series.Legend = secondLegend
            xyView.Pane = secondPane
        End Sub
    End Class
End Namespace